//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace labs_1_4_DistributedSystemsSoftware
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class labDB : DbContext
    {
        public labDB()
            : base("name=labDB")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__RefactorLog> C__RefactorLog { get; set; }
        public virtual DbSet<Authors> Authors { get; set; }
        public virtual DbSet<Songs> Songs { get; set; }
        public virtual DbSet<Songs_descriptions> Songs_descriptions { get; set; }
        public virtual DbSet<values_table> values_table { get; set; }
    }
}
