//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace labs_1_4_DistributedSystemsSoftware
{
    using System;
    using System.Collections.Generic;
    
    public partial class values_table
    {
        public int Id { get; set; }
        public int value { get; set; }
    }
}
